// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMzJRftBvmP2w7kFRwpWlv-nDe4OegCBQ',
    appId: '1:781542075067:web:b8d7fc3d16521f583c579e',
    messagingSenderId: '781542075067',
    projectId: 'authentuto',
    authDomain: 'authentuto.firebaseapp.com',
    storageBucket: 'authentuto.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6FwTWWdJHLx3Fufm1bvip_tDpwGlBp9c',
    appId: '1:781542075067:android:60f8503bda371cb23c579e',
    messagingSenderId: '781542075067',
    projectId: 'authentuto',
    storageBucket: 'authentuto.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9EyIwdVckIlKNKw2ZNyFJ9B77kWcCSUc',
    appId: '1:781542075067:ios:fc6432119238b4513c579e',
    messagingSenderId: '781542075067',
    projectId: 'authentuto',
    storageBucket: 'authentuto.appspot.com',
    iosClientId: '781542075067-36q3hj41phfflef7dno58o49669k05rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9EyIwdVckIlKNKw2ZNyFJ9B77kWcCSUc',
    appId: '1:781542075067:ios:fc6432119238b4513c579e',
    messagingSenderId: '781542075067',
    projectId: 'authentuto',
    storageBucket: 'authentuto.appspot.com',
    iosClientId: '781542075067-36q3hj41phfflef7dno58o49669k05rj.apps.googleusercontent.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
